device: "cuda"
dataset: 
    name: "cub"
    reduced: true
    ex_4_class: 5
output_dim: 200
batch_size: 16
epochs: 200
seed: 42
model: "resnet18"
temperature: 1
geometry: "euclidean"
lam: 0.01
patience: 10
optimizer:
    name: "adam"
    learning_rate: 0.0003
    weight_decay: 0.0003
    momentum: 0.9
lr_scheduler:
    steps:
        - 60
        - 140
        - 160
    entity: 0.2
logger:
    # type: "Local"
    type: "Wandb"
    wandb_args:
         project: "itadata25"
         entity: "mlgroup"
         tags: ["few_data"]
