device: "cpu"
dataset: 
    name: "cifar100"
    reduced: false
    ex_4_class: None
output_dim: 8
batch_size: 128
epochs: 1
seed: 0
model: "resnet18"
temperature: 1.0
geometry: "euclidean"
patience: 5
optimizer:
    name: "sgd"
    learning_rate: 0.1
    weight_decay: 0.0001
    momentum: 0.9
lr_scheduler:
    steps:
        - 10
        - 18
    entity: 0.2
logger:
    # type: "Local"
    type: "Wandb"
    wandb_args:
         project: "itadata25"
         entity: "mlgroup"
