device: "cpu"
dataset: "mnist"
validation: false
output_dim: 8
batch_size: 128
epochs: 20
seed: 0
model: "simplecnn"
save_model: false
eval_every: 5
temperature: 1.0
geometry: "hyperspherical"
optimizer:
    name: "rsgd"
    learning_rate: 0.1
    weight_decay: 0.0001
    momentum: 0.9
lr_scheduler:
    steps:
        - 10
        - 18
    entity: 0.2
logger:
    type: "Local"
    // type: "Wandb"
    // wandb_args:
    //     project: "proto_bench"
    //     entity: "mlgroup"
