device: "cuda"
dataset: 
    name: "aircraft"
    reduced: false
    ex_4_class: 5
output_dim: 100
batch_size: 64
epochs: 200
seed: 42
model: "resnet18"
temperature: 0.05
geometry: "euclidean"
lam: 1.0
patience: 10
optimizer:
    name: "sgd"
    learning_rate: 0.1
    weight_decay: 0.0001
    momentum: 0.9
lr_scheduler:
    steps:
        - 60
        - 140
        - 160
    entity: 0.2
logger:
    # type: "Local"
    type: "Wandb"
    wandb_args:
         project: "itadata25"
         entity: "mlgroup"
